### ISSUE TITLE
Add Rust and Go and it will be OP

### ISSUE THREAD

**Issue by Demuirgos** [sqrt-minus-one/4coder-langs#1]

**Comment by sqrt-negativeone** [comment]
I already have a rust support that is based on [this one](https://github.com/luleyleo/4coder-rust), I'll push it in a moment X)

**Comment by sqrt-negativeone** [comment]
added here 316501be842ddfdfa20e16b1aedba62832cd898d
For Go I may add it if I had to use it in the future lol for now I'm not planning to.
